apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: jenkins
spec:
  destination:
    server: https://kubernetes.default.svc
    namespace: jenkins
  project: default
  source:
    repoURL: https://charts.jenkins.io
    targetRevision: main
    helm:
      valueFiles:
        - values.yaml
    path: jenkins
    chart: jenkins